
import type { Product, Review, Testimonial } from './types';

export const products: Product[] = [
  {
    id: 'canon-g7x-mark-iii',
    name: 'Canon PowerShot G7 X Mark III',
    brand: 'Canon',
    category: 'compact',
    price: 680,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    imageHints: ['compact camera', 'camera screen'],
    condition: 'Excellent',
    description: 'A vlogging powerhouse with live streaming capabilities and a versatile zoom lens.',
    longDescription: 'Perfect for vloggers and content creators, this Canon PowerShot G7 X Mark III is in excellent condition. It features a 20.1MP 1" Stacked CMOS sensor, 4K video recording, and a flip-up touchscreen ideal for selfies and vlogging. Its ability to live stream directly to YouTube makes it a unique and powerful tool for creators.',
    specs: [
      { key: 'Sensor', value: '20.1MP 1" Stacked CMOS' },
      { key: 'Lens', value: '24-100mm (35mm equiv.) f/1.8-2.8' },
      { key: 'Video', value: '4K 30p, Full HD 120p' },
      { key: 'Features', value: 'YouTube Live Streaming, Vertical Video' },
    ],
    warranty: '1-Year ReFocus Warranty',
    rating: 4.7,
    reviewCount: 150,
    reviews: [
        { id: 'r1', author: 'VlogLife', rating: 5, comment: 'The best compact camera for YouTube. So easy to use.', date: '2023-11-05' },
    ],
  },
  {
    id: 'sony-rx100-vii',
    name: 'Sony Cyber-shot RX100 VII',
    brand: 'Sony',
    category: 'compact',
    price: 1050,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    imageHints: ['Sony compact', 'camera lens extended'],
    condition: 'Excellent',
    description: 'Pro-level performance in your pocket, with lightning-fast autofocus and a versatile zoom.',
    longDescription: 'This Sony RX100 VII packs the power of a professional camera into a tiny body. It boasts a 20.1MP sensor, a 24-200mm zoom lens, and Sony\'s industry-leading Real-time Tracking and Eye AF. It\'s in excellent condition and is perfect for travel, portraits, and action.',
    specs: [
      { key: 'Sensor', value: '20.1MP 1" Exmor RS BSI CMOS' },
      { key: 'Lens', value: 'ZEISS 24-200mm (35mm equiv.) f/2.8-4.5' },
      { key: 'Autofocus', value: '357-Point Fast Hybrid AF' },
      { key: 'Video', value: '4K HDR (HLG), S-Log3' },
    ],
    warranty: '1-Year ReFocus Warranty',
    rating: 4.9,
    reviewCount: 180,
    reviews: [
        { id: 'r2', author: 'TravelerTom', rating: 5, comment: 'I can\'t believe the power in this little camera. Replaced my whole DSLR kit.', date: '2023-12-01' },
    ],
  },
  {
    id: 'sony-zv-1',
    name: 'Sony ZV-1',
    brand: 'Sony',
    category: 'compact',
    price: 480,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    imageHints: ['vlogging camera', 'camera with microphone'],
    condition: 'Good',
    description: 'Designed from the ground up for content creators and vloggers.',
    longDescription: 'The Sony ZV-1 is the ultimate vlogging camera. This unit is in good condition with minor signs of wear. It features a side flip-out screen, a directional 3-capsule microphone with a windscreen, and unique features like Product Showcase Setting and Background Defocus. Instantly create professional-looking videos with ease.',
    specs: [
      { key: 'Sensor', value: '20.1MP 1" Exmor RS BSI CMOS' },
      { key: 'Lens', value: '24-70mm (35mm equiv.) f/1.8-2.8' },
      { key: 'Features', value: 'Product Showcase, Background Defocus' },
      { key: 'Audio', value: 'Directional 3-Capsule Mic & Wind Screen' },
    ],
    warranty: '6-Month ReFocus Warranty',
    rating: 4.8,
    reviewCount: 250,
    reviews: [],
  },
  {
    id: 'panasonic-lx10',
    name: 'Panasonic Lumix DMC-LX10',
    brand: 'Panasonic',
    category: 'compact',
    price: 640,
    images: ['https://placehold.co/600x600.png'],
    imageHints: ['Panasonic camera'],
    condition: 'Good',
    description: 'A premium compact with a fast lens and 4K video capabilities.',
    longDescription: 'This Lumix LX10 is in good condition. It features a bright f/1.4-2.8 Leica DC Vario-Summilux lens and a 20.1MP 1-inch MOS sensor for stunning photos, even in low light. Its 4K video and Photo capabilities make it a versatile tool for any photographer.',
    specs: [
      { key: 'Sensor', value: '20.1MP 1" MOS' },
      { key: 'Lens', value: 'Leica DC 24-72mm (35mm equiv.) f/1.4-2.8' },
      { key: 'Video', value: '4K 30p' },
      { key: 'Features', value: '5-Axis Hybrid O.I.S.+, Post Focus' },
    ],
    warranty: '6-Month ReFocus Warranty',
    rating: 4.6,
    reviewCount: 90,
    reviews: [],
  },
  {
    id: 'ricoh-gr-iii',
    name: 'Ricoh GR III',
    brand: 'Ricoh',
    category: 'compact',
    price: 880,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    imageHints: ['street camera', 'minimalist camera'],
    condition: 'Excellent',
    description: 'The ultimate pocketable camera for street photography, delivering incredible image quality.',
    longDescription: 'The Ricoh GR III is a cult classic for a reason. This model is in excellent condition. It features a large 24.2MP APS-C sensor in a body that fits in your pocket. With a sharp 28mm equivalent lens, in-body stabilization, and intuitive controls, it\'s designed for fast, discreet, high-quality shooting.',
    specs: [
      { key: 'Sensor', value: '24.2MP APS-C CMOS' },
      { key: 'Lens', value: '28mm (35mm equiv.) f/2.8' },
      { key: 'Stabilization', value: '3-Axis Shake Reduction' },
      { key: 'Size', value: '4.3 x 2.4 x 1.3 inches' },
    ],
    warranty: '1-Year ReFocus Warranty',
    rating: 4.9,
    reviewCount: 210,
    reviews: [],
  },
  {
    id: 'fujifilm-x100v',
    name: 'Fujifilm X100V',
    brand: 'Fujifilm',
    category: 'compact',
    price: 1650,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    imageHints: ['retro camera', 'Fujifilm X100V'],
    condition: 'Excellent',
    description: 'A beautifully designed camera with a unique hybrid viewfinder and Fuji\'s beloved film simulations.',
    longDescription: 'The highly sought-after Fujifilm X100V, in excellent condition. This camera combines stunning retro design with modern technology. It has a 26.1MP APS-C sensor, a redesigned sharp 23mm f/2 lens, and a tilting touchscreen. The Advanced Hybrid Viewfinder lets you switch between optical and electronic views, offering a unique shooting experience.',
    specs: [
      { key: 'Sensor', value: '26.1MP APS-C X-Trans BSI CMOS 4' },
      { key: 'Lens', value: '23mm (35mm equiv.) f/2' },
      { key: 'Viewfinder', value: 'Advanced Hybrid Optical and Electronic' },
      { key: 'Features', value: 'Classic Film Simulations, Tilting LCD' },
    ],
    warranty: '1-Year ReFocus Warranty',
    rating: 5.0,
    reviewCount: 350,
    reviews: [],
  },
  {
    id: 'panasonic-lumix-zs100',
    name: 'Panasonic Lumix ZS100',
    brand: 'Panasonic',
    category: 'compact',
    price: 500,
    images: ['https://placehold.co/600x600.png'],
    imageHints: ['travel zoom camera'],
    condition: 'Good',
    description: 'The perfect travel companion with a 10x zoom and 1-inch sensor.',
    longDescription: 'This Panasonic Lumix ZS100 is in good condition and ready for your next adventure. It pairs a 20.1MP 1-inch sensor with a 10x Leica DC Vario-Elmarit zoom lens (25-250mm equiv.), giving you incredible versatility in a pocket-sized package. It also shoots 4K video and offers full manual controls.',
    specs: [
      { key: 'Sensor', value: '20.1MP 1" MOS' },
      { key: 'Lens', value: 'Leica DC 25-250mm (35mm equiv.) f/2.8-5.9' },
      { key: 'Video', value: '4K 30p' },
      { key: 'Features', value: 'Electronic Viewfinder, Wi-Fi' },
    ],
    warranty: '6-Month ReFocus Warranty',
    rating: 4.5,
    reviewCount: 110,
    reviews: [],
  },
];


export const testimonials: Testimonial[] = [
    {
        id: 't1',
        quote: 'My camera arrived looking brand new, and the customer service was fantastic. I\'m so impressed with the quality and the price. Will definitely be coming back for my next lens!',
        author: 'Sarah J.',
        location: 'New York, NY',
        rating: 5,
        image: 'https://placehold.co/100x100.png',
        imageHint: 'happy customer'
    },
    {
        id: 't2',
        quote: 'I was hesitant about buying refurbished, but ReFocus changed my mind. The gear is top-notch, and their 1-year warranty gave me total peace of mind. Highly recommended.',
        author: 'Mike R.',
        location: 'Austin, TX',
        rating: 5,
        image: 'https://placehold.co/100x100.png',
        imageHint: 'customer portrait'
    },
    {
        id: 't3',
        quote: 'The whole process was smooth, from finding the right camera to the super-fast shipping. The condition was exactly as described. It\'s a sustainable and smart way to buy tech.',
        author: 'Chloe B.',
        location: 'San Francisco, CA',
        rating: 5,
        image: 'https://placehold.co/100x100.png',
        imageHint: 'woman smiling'
    }
];
