import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'canon-eos-5d-mark-iv',
    name: 'Canon EOS 5D Mark IV',
    brand: 'Canon',
    category: 'dslr',
    price: 1799.99,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    imageHints: ['camera body', 'camera angle', 'camera back'],
    condition: 'Excellent',
    description: 'A versatile workhorse, the EOS 5D Mark IV is a favorite among professionals for its stunning image quality and robust build.',
    longDescription: 'This Canon EOS 5D Mark IV is in excellent condition, showing minimal signs of use. It has been fully tested and cleaned by our expert technicians. The camera delivers outstanding image quality with its 30.4 Megapixel full-frame sensor and 4K video capability. It\'s a reliable choice for both photographers and videographers looking for professional-grade performance without the brand-new price tag.',
    specs: [
      { key: 'Sensor', value: '30.4MP Full-Frame CMOS' },
      { key: 'Processor', value: 'DIGIC 6+' },
      { key: 'ISO Range', value: '100-32000 (Expandable to 50-102400)' },
      { key: 'Autofocus', value: '61-Point High-Density Reticular AF' },
      { key: 'Video', value: 'DCI 4K at 30 fps' },
      { key: 'Shutter Count', value: 'Approx. 25,000' },
    ],
    warranty: '1-Year ReFocus Warranty',
    rating: 4.8,
    reviewCount: 128,
    reviews: [
      { id: 'r1', author: 'Jane D.', rating: 5, comment: 'Camera is practically new! Incredible value.', date: '2023-10-15' },
      { id: 'r2', author: 'Mike P.', rating: 4, comment: 'Great camera, works perfectly. Minor scuff on the bottom but that was expected.', date: '2023-09-22' },
    ],
  },
  {
    id: 'nikon-d850',
    name: 'Nikon D850',
    brand: 'Nikon',
    category: 'dslr',
    price: 1999.99,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    imageHints: ['DSLR camera', 'Nikon camera', 'camera side'],
    condition: 'Good',
    description: 'Unleash your creative potential with the Nikon D850, boasting exceptional resolution and speed.',
    longDescription: 'This Nikon D850 is in good condition, with some visible signs of cosmetic wear such as light scratches on the body, but is fully operational and functions as intended. Its massive 45.7MP sensor captures breathtaking detail, and the fast EXPEED 5 processor keeps up with the action. An amazing tool for landscape, studio, and wedding photography.',
    specs: [
      { key: 'Sensor', value: '45.7MP FX-Format BSI CMOS' },
      { key: 'Processor', value: 'EXPEED 5' },
      { key: 'ISO Range', value: '64-25600 (Expandable to 32-102400)' },
      { key: 'Autofocus', value: '153-Point AF System' },
      { key: 'Video', value: '4K UHD at 30 fps' },
      { key: 'Shutter Count', value: 'Approx. 65,000' },
    ],
    warranty: '6-Month ReFocus Warranty',
    rating: 4.7,
    reviewCount: 95,
    reviews: [
      { id: 'r3', author: 'Sam T.', rating: 5, comment: 'A beast of a camera. The image quality is insane.', date: '2023-11-01' },
      { id: 'r4', author: 'Emily R.', rating: 4, comment: 'Performs like a champ. Wish the warranty was longer.', date: '2023-10-05' },
    ],
  },
  {
    id: 'sony-alpha-a7-iii',
    name: 'Sony Alpha a7 III',
    brand: 'Sony',
    category: 'mirrorless',
    price: 1450.00,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    imageHints: ['mirrorless camera', 'Sony camera', 'camera top'],
    condition: 'Excellent',
    description: 'The perfect blend of power and portability, the Sony a7 III is a master of all trades in the mirrorless world.',
    longDescription: 'In pristine, excellent condition, this Sony a7 III is a modern classic. It features a 24.2MP full-frame sensor, incredible autofocus performance with 693 phase-detection points, and 5-axis in-body image stabilization. It\'s a fantastic hybrid camera, excelling at both still photography and 4K video, all in a compact package.',
    specs: [
      { key: 'Sensor', value: '24.2MP Full-Frame Exmor R BSI CMOS' },
      { key: 'Processor', value: 'BIONZ X' },
      { key: 'ISO Range', value: '100-51200 (Expandable to 50-204800)' },
      { key: 'Autofocus', value: 'Fast Hybrid AF with 693 Phase-Detect Points' },
      { key: 'Video', value: 'UHD 4K at 30 fps' },
      { key: 'Shutter Count', value: 'Approx. 15,000' },
    ],
    warranty: '1-Year ReFocus Warranty',
    rating: 4.9,
    reviewCount: 210,
    reviews: [
      { id: 'r5', author: 'Chris G.', rating: 5, comment: 'Best camera I have ever owned. The autofocus is magic.', date: '2023-11-10' },
      { id: 'r6', author: 'Olivia W.', rating: 5, comment: 'Flawless condition and works beautifully. Highly recommend!', date: '2023-10-20' },
    ],
  },
  {
    id: 'fujifilm-x-t4',
    name: 'Fujifilm X-T4',
    brand: 'Fujifilm',
    category: 'mirrorless',
    price: 1299.00,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    imageHints: ['retro camera', 'Fujifilm camera', 'camera dial'],
    condition: 'Fair',
    description: 'A stylish and capable camera offering beautiful film simulations and advanced video features.',
    longDescription: 'This Fujifilm X-T4 is in fair condition. It has noticeable cosmetic signs of use, including scratches and scuffs on the body and screen, but it has been tested to be fully functional. It offers in-body image stabilization, a flip-out screen, and Fujifilm\'s renowned color science. A great choice for a creative shooter who values performance over perfect looks.',
    specs: [
      { key: 'Sensor', value: '26.1MP APS-C X-Trans BSI CMOS 4' },
      { key: 'Processor', value: 'X-Processor 4' },
      { key: 'ISO Range', value: '160-12800 (Expandable to 80-51200)' },
      { key: 'Stabilization', value: '5-Axis In-Body Image Stabilization' },
      { key: 'Video', value: 'DCI/UHD 4K at 60 fps' },
      { key: 'Shutter Count', value: 'Approx. 80,000' },
    ],
    warranty: '3-Month ReFocus Warranty',
    rating: 4.5,
    reviewCount: 76,
    reviews: [
      { id: 'r7', author: 'Ben S.', rating: 4, comment: 'It\'s definitely seen some love, but it works great and the photos are amazing.', date: '2023-09-01' },
      { id: 'r8', author: 'Laura K.', rating: 5, comment: 'Couldn\'t be happier for the price. The functionality is all there.', date: '2023-08-18' },
    ],
  },
  {
    id: 'canon-ef-50mm-f1-8',
    name: 'Canon EF 50mm f/1.8 STM Lens',
    brand: 'Canon',
    category: 'lenses',
    price: 99.00,
    images: ['https://placehold.co/600x600.png'],
    imageHints: ['camera lens'],
    condition: 'Excellent',
    description: 'The "nifty fifty" is a must-have for any photographer, offering sharp images and beautiful bokeh.',
    longDescription: 'In excellent condition, this Canon EF 50mm f/1.8 STM lens is a fantastic and affordable prime lens. It\'s lightweight, compact, and perfect for portraits, street photography, and low-light situations. The stepping motor (STM) provides smooth and quiet autofocus, which is also great for video.',
    specs: [
      { key: 'Lens Mount', value: 'Canon EF' },
      { key: 'Focal Length', value: '50mm' },
      { key: 'Maximum Aperture', value: 'f/1.8' },
      { key: 'Minimum Aperture', value: 'f/22' },
      { key: 'Autofocus', value: 'STM Motor' },
    ],
    warranty: '1-Year ReFocus Warranty',
    rating: 4.9,
    reviewCount: 532,
    reviews: [],
  },
  {
    id: 'peak-design-tripod',
    name: 'Peak Design Travel Tripod',
    brand: 'Peak Design',
    category: 'accessories',
    price: 280.00,
    images: ['https://placehold.co/600x600.png'],
    imageHints: ['camera tripod'],
    condition: 'Good',
    description: 'A professional travel tripod that is compact, stable, and quick to set up.',
    longDescription: 'This Peak Design Travel Tripod (Aluminum) is in good, fully functional condition with some signs of use on the legs. It packs down to the diameter of a water bottle without sacrificing height or stability. It\'s an engineering marvel that will be a trusty companion on all your adventures.',
    specs: [
      { key: 'Material', value: 'Aluminum Alloy' },
      { key: 'Max Height', value: '60" (152.4 cm)' },
      { key: 'Folded Length', value: '15.4" (39.1 cm)' },
      { key: 'Weight', value: '3.44 lbs (1.56 kg)' },
      { key: 'Load Capacity', value: '20 lbs (9.1 kg)' },
    ],
    warranty: '6-Month ReFocus Warranty',
    rating: 4.7,
    reviewCount: 45,
    reviews: [],
  },
];
